<?php $theme_dir = dirname(__DIR__, 2) . '/theme/'; ?>
                    </div>
                </div>
                <div id="navcol" class="ie7fix">
                    <?php require($theme_dir . "includes/navcol.html"); ?>
                </div>
                <div id="extracol">
                    <?php require($theme_dir . "includes/extracol.html"); ?>
                </div>
            </div>
        </div>
        <div id="footer">
            <?php require($theme_dir . "includes/footer.html"); ?>
        </div>
        <div id="postfooter" class="containfloats">
            <?php require($theme_dir . "includes/postfooter.html"); ?>
        </div>
    </body>
</html>
<!--
Copyright 2010-2011 Joshua Simmons

All rights reserved
-->
